version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 6
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 300
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 30
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
  identical-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
plugins:
 pep8:
  enabled: false
exclude_patterns:
- "config/"
- "db/"
- "dist/"
- "**/.*"
- "**/data/"
- "**/runScripts/"
- "**/tinyHelper/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "Tests/"
- "docs/"
- "benchmarks/"
- "**/vendor/"
- "**/*_test.go"
- "**/*.d.ts"
- "**/*.cint"
- "**/*.yml"
- "**/*.ini"
- "**/*.json"
- "**/*.txt"
- "**/*.conf"
- ".github/"
