github_checks:
    annotations: false

coverage:
  status:
    project:
      default:
        informational: true 
        target: auto
        threshold: 0%
    patch:
      default:
        informational: true
        target: auto
        threshold: 0%

ignore:
  - "**/run*.py"
