github_checks:
    annotations: false

coverage:
  status:
    project:
      default:
        informational: false 
        target: auto
        threshold: 0%
    patch:
      default:
        informational: false
        target: auto
        threshold: 0%

ignore:
  - "**/run*.py"
